# Generated by Django 3.1.6 on 2021-02-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210212_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='speakerid',
            field=models.CharField(db_index=True, max_length=64, verbose_name='speakerid'),
        ),
    ]
