# Generated by Django 3.1.6 on 2021-02-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210212_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='speakerid',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='speakerid'),
        ),
    ]
