# Generated by Django 3.1.6 on 2021-02-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_speaker_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='publish',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='speakerid',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='серийный номер'),
        ),
    ]
